spring.application.name=studentapp

# H2 Database
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver

# JPA
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

# IMPORTANT FIX
spring.jpa.defer-datasource-initialization=true

# H2 Console
spring.h2.console.enabled=true



